# swagger.yml

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "A simple REST API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Person:
      type: "object"
      required:
        - lname
      properties:
        fname:
          type: "string"
        lname:
          type: "string"

paths:
  /people:
    get:
      operationId: "people.read_all"
      tags:
        - "People"
      summary: "read the list of people"
      responses:
        "200":
          description: "Successfully read people list"